# Generated by Django 4.2.6 on 2023-10-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
