# Generated by Django 4.2.6 on 2023-10-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distri', '0002_leches_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galletitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
            ],
        ),
    ]
