# Generated by Django 4.2.6 on 2023-10-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distri', '0003_galletitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='galletitas',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leches',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
